#!/bin/bash
# Deployment daemon
# chkconfig: 345 20 80
# description: Manages the komodo-web-deploy instance, basically just wraps "forever"
# processname: ko-deploy

DAEMON_PATH="/deployment/komodo-web-deploy"
DAEMON="node server.js"
NAME="ko-deploy"

case "$1" in
start)
    $0 restart
;;
status)
    "$DAEMON_PATH/node_modules/forever/bin/forever list"
;;
stop)
    "$DAEMON_PATH/node_modules/forever/bin/forever stop $DAEMON_PATH/server.js"
;;

restart)
    $0 stop
    "$DAEMON_PATH/node_modules/forever/bin/forever start $DAEMON_PATH/server.js"
    $0 status
;;

*)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac
